	<!-- CSS here -->
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/animate.min.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/magnific-popup.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/fontawesome-all.min.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/jquery.mCustomScrollbar.min.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/bootstrap-datepicker.min.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/swiper-bundle.min.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/jquery-ui.min.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/nice-select.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/jarallax.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/flaticon.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/slick.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/default.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/style.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('/Ecommerce/css/responsive.css')}}">